"""
This type stub file was generated by pyright.
"""

from . import ws2_32 as ws2_32
from . import oleaut32 as oleaut32

ords: dict[bytes, dict[int, bytes]] = ...

def formatOrdString(ord_val: bytes) -> bytes: ...
def ordLookup(libname: str, ord_val: bytes, make_name: bool = ...) -> bytes | None: ...
